---
all:
  children:
    web1:
  vars:
    ansible_ssh_private_key_file: client.pem

web1:
  hosts:
    web01:
      ansible_host: 172.31.10.134
      ansible_user: ubuntu                            
